"""Add Hotel model

Revision ID: 35fa6f5a770b
Revises: 435eef02c8f3
Create Date: 2025-11-27 23:00:07.153539

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '35fa6f5a770b'
down_revision = '435eef02c8f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('clauses',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('document_id', sa.Integer(), nullable=False),
    # sa.Column('text', sa.Text(), nullable=False),
    # sa.Column('tags', sa.JSON(), nullable=True),
    # sa.Column('clause_ref', sa.String(length=100), nullable=True),
    # sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    # sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_clauses_document_id'), 'clauses', ['document_id'], unique=False)
    # op.create_index(op.f('ix_clauses_id'), 'clauses', ['id'], unique=False)
    op.create_table('hotels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('manager_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('price_quote', sa.String(length=100), nullable=True),
    sa.Column('unread_count', sa.Integer(), nullable=True),
    sa.Column('last_contact_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotels_id'), 'hotels', ['id'], unique=False)
    op.create_index(op.f('ix_hotels_opportunity_id'), 'hotels', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_hotels_status'), 'hotels', ['status'], unique=False)
    # op.drop_index(op.f('idx_hs_geo'), table_name='hotel_suggestions')
    # op.drop_index(op.f('idx_hs_notice'), table_name='hotel_suggestions')
    # op.drop_index(op.f('idx_hs_score'), table_name='hotel_suggestions')
    # op.drop_table('hotel_suggestions')
    # op.drop_table('system_metrics')
    # op.drop_table('hotel_resource_links')
    # op.drop_table('document_opportunity_relations')
    # op.drop_table('hotel_opportunities_new')
    # op.drop_table('sam_subcontracts')
    # op.drop_table('keywords')
    # op.drop_index(op.f('idx_structured_requirements_active'), table_name='structured_requirements')
    # op.drop_index(op.f('idx_structured_requirements_category'), table_name='structured_requirements')
    # op.drop_index(op.f('idx_structured_requirements_metadata'), table_name='structured_requirements', postgresql_using='gin')
    # op.drop_index(op.f('idx_structured_requirements_notice_id'), table_name='structured_requirements')
    # op.drop_index(op.f('idx_structured_requirements_type'), table_name='structured_requirements')
    # op.drop_table('structured_requirements')
    # op.drop_index(op.f('idx_osm_cache_created'), table_name='osm_cache')
    # op.drop_table('osm_cache')
    # op.drop_table('opportunity_docs')
    # op.drop_index(op.f('idx_sow_active'), table_name='sow_analysis')
    # op.drop_index(op.f('idx_sow_breakout_count'), table_name='sow_analysis', postgresql_where='(is_active = true)')
    # op.drop_index(op.f('idx_sow_capacity'), table_name='sow_analysis', postgresql_where='(is_active = true)')
    # op.drop_index(op.f('idx_sow_payload_gin'), table_name='sow_analysis', postgresql_using='gin')
    # op.drop_index(op.f('idx_vw_active_sow_notice_id'), table_name='sow_analysis', postgresql_where='(is_active = true)')
    # op.drop_index(op.f('uq_sow_notice_template'), table_name='sow_analysis')
    # op.drop_table('sow_analysis')
    # op.drop_table('document_analysis_results')
    # op.drop_index(op.f('idx_user_sessions_session_id'), table_name='user_sessions')
    # op.drop_table('user_sessions')
    # op.drop_table('summaries')
    # op.drop_index(op.f('idx_manual_documents_notice_id'), table_name='manual_documents')
    # op.drop_table('manual_documents')
    # op.drop_index(op.f('idx_hotel_chunks_embedding_version'), table_name='hotel_chunks')
    # op.drop_index(op.f('idx_hotel_chunks_notice_id'), table_name='hotel_chunks')
    # op.drop_table('hotel_chunks')
    # op.drop_index(op.f('idx_kf_created'), table_name='knowledge_facts')
    # op.drop_index(op.f('idx_kf_gin'), table_name='knowledge_facts', postgresql_using='gin')
    # op.drop_index(op.f('idx_kf_notice'), table_name='knowledge_facts')
    # op.drop_index(op.f('idx_kf_schema'), table_name='knowledge_facts')
    # op.drop_table('knowledge_facts')
    # op.drop_table('proposals')
    # op.create_index(op.f('ix_agent_messages_created_at'), 'agent_messages', ['created_at'], unique=False)
    # op.create_index(op.f('ix_agent_messages_id'), 'agent_messages', ['id'], unique=False)
    # op.create_index(op.f('ix_agent_runs_id'), 'agent_runs', ['id'], unique=False)
    # op.drop_column('agent_runs', 'metadata')
    # op.alter_column('analysis_logs', 'timestamp',
    #            existing_type=postgresql.TIMESTAMP(),
    #            type_=sa.DateTime(timezone=True),
    #            existing_nullable=True,
    #            existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # op.create_index(op.f('ix_analysis_logs_analysis_result_id'), 'analysis_logs', ['analysis_result_id'], unique=False)
    # op.create_index(op.f('ix_analysis_logs_id'), 'analysis_logs', ['id'], unique=False)
    # op.create_index(op.f('ix_analysis_logs_level'), 'analysis_logs', ['level'], unique=False)
    # op.create_index(op.f('ix_analysis_logs_timestamp'), 'analysis_logs', ['timestamp'], unique=False)
    # op.create_foreign_key(None, 'analysis_logs', 'ai_analysis_results', ['analysis_result_id'], ['id'], ondelete='CASCADE')
    # op.create_index(op.f('ix_decision_cache_id'), 'decision_cache', ['id'], unique=False)
    # op.drop_column('decision_cache', 'metadata')
    # op.add_column('documents', sa.Column('kind', sa.String(length=100), nullable=False))
    # op.add_column('documents', sa.Column('title', sa.String(length=512), nullable=False))
    # op.add_column('documents', sa.Column('path', sa.String(length=1024), nullable=False))
    # op.add_column('documents', sa.Column('meta_json', sa.JSON(), nullable=True))
    # op.add_column('documents', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # op.add_column('documents', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    # op.create_index(op.f('ix_documents_kind'), 'documents', ['kind'], unique=False)
    # op.drop_constraint(op.f('documents_opportunity_id_fkey'), 'documents', type_='foreignkey')
    # op.drop_column('documents', 'document_name')
    # op.drop_column('documents', 'download_date')
    # op.drop_column('documents', 'file_size')
    # op.drop_column('documents', 'file_path')
    # op.drop_column('documents', 'opportunity_id')
    # op.drop_column('documents', 'document_url')
    # op.drop_column('documents', 'processed')
    # op.create_index(op.f('ix_email_log_id'), 'email_log', ['id'], unique=False)
    op.create_foreign_key(None, 'email_log', 'hotels', ['hotel_id'], ['id'], ondelete='SET NULL')
    # op.add_column('evidence', sa.Column('extra_metadata', sa.JSON(), nullable=True))
    # op.alter_column('evidence', 'source_doc_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True)
    # op.alter_column('evidence', 'snippet',
    #            existing_type=sa.TEXT(),
    #            nullable=True)
    # op.alter_column('evidence', 'created_at',
    #            existing_type=postgresql.TIMESTAMP(),
    #            type_=sa.DateTime(timezone=True),
    #            nullable=False,
    #            existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # op.drop_index(op.f('idx_evidence_requirement_id'), table_name='evidence')
    # op.create_index(op.f('ix_evidence_id'), 'evidence', ['id'], unique=False)
    # op.create_index(op.f('ix_evidence_requirement_id'), 'evidence', ['requirement_id'], unique=False)
    # op.create_index(op.f('ix_evidence_source_doc_id'), 'evidence', ['source_doc_id'], unique=False)
    # op.create_foreign_key(None, 'evidence', 'documents', ['source_doc_id'], ['id'], ondelete='SET NULL')
    # op.create_foreign_key(None, 'evidence', 'requirements', ['requirement_id'], ['id'], ondelete='CASCADE')
    # op.add_column('facility_features', sa.Column('category', sa.String(length=50), nullable=True))
    # op.alter_column('facility_features', 'name',
    #            existing_type=sa.VARCHAR(length=255),
    #            type_=sa.String(length=100),
    #            existing_nullable=False)
    # op.alter_column('facility_features', 'value',
    #            existing_type=sa.TEXT(),
    #            nullable=False)
    # op.alter_column('facility_features', 'created_at',
    #            existing_type=postgresql.TIMESTAMP(),
    #            type_=sa.DateTime(timezone=True),
    #            nullable=False,
    #            existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # op.create_index(op.f('ix_facility_features_id'), 'facility_features', ['id'], unique=False)
    # op.create_index(op.f('ix_facility_features_source_doc_id'), 'facility_features', ['source_doc_id'], unique=False)
    # op.create_foreign_key(None, 'facility_features', 'documents', ['source_doc_id'], ['id'], ondelete='CASCADE')
    # op.create_index(op.f('ix_llm_calls_id'), 'llm_calls', ['id'], unique=False)
    # op.alter_column('opportunities', 'posted_date',
    #            existing_type=postgresql.TIMESTAMP(),
    #            type_=sa.DateTime(timezone=True),
    #            existing_nullable=True)
    # op.alter_column('opportunities', 'response_deadline',
    #            existing_type=postgresql.TIMESTAMP(),
    #            type_=sa.DateTime(timezone=True),
    #            existing_nullable=True)
    # op.alter_column('opportunities', 'agency',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=255),
    #            existing_nullable=True)
    # op.alter_column('opportunities', 'office',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=255),
    #            existing_nullable=True)
    # op.alter_column('opportunities', 'estimated_value',
    #            existing_type=sa.NUMERIC(precision=15, scale=2),
    #            type_=sa.Float(),
    #            existing_nullable=True)
    # op.alter_column('opportunities', 'status',
    #            existing_type=sa.VARCHAR(length=50),
    #            nullable=False,
    #            existing_server_default=sa.text("'active'::character varying"))
    # op.alter_column('opportunities', 'raw_data',
    #            existing_type=postgresql.JSONB(astext_type=sa.Text()),
    #            type_=sa.JSON(),
    #            existing_nullable=True)
    # op.alter_column('opportunities', 'cached_data',
    #            existing_type=postgresql.JSONB(astext_type=sa.Text()),
    #            type_=sa.JSON(),
    #            existing_nullable=True)
    # op.alter_column('opportunities', 'cache_updated_at',
    #            existing_type=postgresql.TIMESTAMP(),
    #            type_=sa.DateTime(timezone=True),
    #            existing_nullable=True)
    # op.alter_column('opportunities', 'created_at',
    #            existing_type=postgresql.TIMESTAMP(),
    #            type_=sa.DateTime(timezone=True),
    #            existing_nullable=True,
    #            existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # op.alter_column('opportunities', 'updated_at',
    #            existing_type=postgresql.TIMESTAMP(),
    #            type_=sa.DateTime(timezone=True),
    #            existing_nullable=True,
    #            existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # op.drop_index(op.f('idx_opportunities_notice_id'), table_name='opportunities')
    # op.drop_index(op.f('idx_opportunities_posted_date'), table_name='opportunities')
    # op.drop_index(op.f('idx_opportunities_solicitation_number'), table_name='opportunities')
    # op.drop_constraint(op.f('opportunities_opportunity_id_key'), 'opportunities', type_='unique')
    # op.create_index(op.f('ix_opportunities_id'), 'opportunities', ['id'], unique=False)
    # op.create_index(op.f('ix_opportunities_naics_code'), 'opportunities', ['naics_code'], unique=False)
    # op.create_index(op.f('ix_opportunities_notice_id'), 'opportunities', ['notice_id'], unique=False)
    # op.create_index(op.f('ix_opportunities_opportunity_id'), 'opportunities', ['opportunity_id'], unique=False)
    # op.create_index(op.f('ix_opportunities_posted_date'), 'opportunities', ['posted_date'], unique=False)
    # op.create_index(op.f('ix_opportunities_solicitation_number'), 'opportunities', ['solicitation_number'], unique=False)
    # op.alter_column('opportunity_attachments', 'name',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=512),
    #            existing_nullable=False)
    # op.alter_column('opportunity_attachments', 'source_url',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=1024),
    #            existing_nullable=True)
    # op.alter_column('opportunity_attachments', 'attachment_type',
    #            existing_type=sa.VARCHAR(length=50),
    #            nullable=True,
    #            existing_server_default=sa.text("'document'::character varying"))
    # op.alter_column('opportunity_attachments', 'local_path',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=1024),
    #            existing_nullable=True)
    # op.alter_column('opportunity_attachments', 'storage_path',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=1024),
    #            existing_nullable=True)
    # op.create_index(op.f('ix_opportunity_history_id'), 'opportunity_history', ['id'], unique=False)
    # op.alter_column('past_performance', 'ref_info',
    #            existing_type=postgresql.JSONB(astext_type=sa.Text()),
    #            type_=sa.JSON(),
    #            existing_nullable=True)
    # op.alter_column('past_performance', 'created_at',
    #            existing_type=postgresql.TIMESTAMP(),
    #            type_=sa.DateTime(timezone=True),
    #            nullable=False,
    #            existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # op.create_index(op.f('ix_past_performance_id'), 'past_performance', ['id'], unique=False)
    # op.alter_column('pricing_items', 'unit_price',
    #            existing_type=sa.DOUBLE_PRECISION(precision=53),
    #            nullable=True)
    # op.alter_column('pricing_items', 'category',
    #            existing_type=sa.VARCHAR(length=50),
    #            type_=sa.String(length=100),
    #            existing_nullable=True)
    # op.alter_column('pricing_items', 'created_at',
    #            existing_type=postgresql.TIMESTAMP(),
    #            type_=sa.DateTime(timezone=True),
    #            nullable=False,
    #            existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # op.create_index(op.f('ix_pricing_items_id'), 'pricing_items', ['id'], unique=False)
    # op.create_index(op.f('ix_pricing_items_rfq_id'), 'pricing_items', ['rfq_id'], unique=False)
    # op.create_foreign_key(None, 'pricing_items', 'documents', ['rfq_id'], ['id'], ondelete='CASCADE')
    # op.add_column('requirements', sa.Column('status', sa.String(length=50), nullable=True))
    # op.add_column('requirements', sa.Column('tags', sa.JSON(), nullable=True))
    # op.alter_column('requirements', 'code',
    #            existing_type=sa.VARCHAR(length=20),
    #            type_=sa.String(length=50),
    #            nullable=True)
    # op.alter_column('requirements', 'category',
    #            existing_type=sa.VARCHAR(length=50),
    #            type_=sa.String(length=100),
    #            existing_nullable=True)
    # op.alter_column('requirements', 'priority',
    #            existing_type=sa.VARCHAR(length=20),
    #            type_=sa.String(length=50),
    #            existing_nullable=True,
    #            existing_server_default=sa.text("'medium'::character varying"))
    # op.alter_column('requirements', 'created_at',
    #            existing_type=postgresql.TIMESTAMP(),
    #            type_=sa.DateTime(timezone=True),
    #            nullable=False,
    #            existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # op.drop_index(op.f('idx_requirements_rfq_id'), table_name='requirements')
    # op.create_index(op.f('ix_requirements_id'), 'requirements', ['id'], unique=False)
    # op.create_index(op.f('ix_requirements_rfq_id'), 'requirements', ['rfq_id'], unique=False)
    # op.create_foreign_key(None, 'requirements', 'documents', ['rfq_id'], ['id'], ondelete='CASCADE')
    # op.create_index(op.f('ix_training_examples_id'), 'training_examples', ['id'], unique=False)
    # op.alter_column('vector_chunks', 'embedding',
    #            existing_type=postgresql.JSONB(astext_type=sa.Text()),
    #            type_=sa.JSON(),
    #            existing_nullable=True)
    # op.alter_column('vector_chunks', 'created_at',
    #            existing_type=postgresql.TIMESTAMP(timezone=True),
    #            nullable=False,
    #            existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # op.drop_index(op.f('idx_vector_chunks_document_id'), table_name='vector_chunks')
    # op.create_index(op.f('ix_vector_chunks_document_id'), 'vector_chunks', ['document_id'], unique=False)
    # op.create_index(op.f('ix_vector_chunks_id'), 'vector_chunks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vector_chunks_id'), table_name='vector_chunks')
    op.drop_index(op.f('ix_vector_chunks_document_id'), table_name='vector_chunks')
    op.create_index(op.f('idx_vector_chunks_document_id'), 'vector_chunks', ['document_id'], unique=False)
    op.alter_column('vector_chunks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('vector_chunks', 'embedding',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_training_examples_id'), table_name='training_examples')
    op.drop_constraint(None, 'requirements', type_='foreignkey')
    op.drop_index(op.f('ix_requirements_rfq_id'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_id'), table_name='requirements')
    op.create_index(op.f('idx_requirements_rfq_id'), 'requirements', ['rfq_id'], unique=False)
    op.alter_column('requirements', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('requirements', 'priority',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('requirements', 'category',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('requirements', 'code',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('requirements', 'tags')
    op.drop_column('requirements', 'status')
    op.drop_constraint(None, 'pricing_items', type_='foreignkey')
    op.drop_index(op.f('ix_pricing_items_rfq_id'), table_name='pricing_items')
    op.drop_index(op.f('ix_pricing_items_id'), table_name='pricing_items')
    op.alter_column('pricing_items', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('pricing_items', 'category',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('pricing_items', 'unit_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_index(op.f('ix_past_performance_id'), table_name='past_performance')
    op.alter_column('past_performance', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('past_performance', 'ref_info',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_opportunity_history_id'), table_name='opportunity_history')
    op.alter_column('opportunity_attachments', 'storage_path',
               existing_type=sa.String(length=1024),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('opportunity_attachments', 'local_path',
               existing_type=sa.String(length=1024),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('opportunity_attachments', 'attachment_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'document'::character varying"))
    op.alter_column('opportunity_attachments', 'source_url',
               existing_type=sa.String(length=1024),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('opportunity_attachments', 'name',
               existing_type=sa.String(length=512),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_opportunities_solicitation_number'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_posted_date'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_opportunity_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_notice_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_naics_code'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_id'), table_name='opportunities')
    op.create_unique_constraint(op.f('opportunities_opportunity_id_key'), 'opportunities', ['opportunity_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_opportunities_solicitation_number'), 'opportunities', ['solicitation_number'], unique=False)
    op.create_index(op.f('idx_opportunities_posted_date'), 'opportunities', ['posted_date'], unique=False)
    op.create_index(op.f('idx_opportunities_notice_id'), 'opportunities', ['notice_id'], unique=False)
    op.alter_column('opportunities', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('opportunities', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('opportunities', 'cache_updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('opportunities', 'cached_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('opportunities', 'raw_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('opportunities', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('opportunities', 'estimated_value',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('opportunities', 'office',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('opportunities', 'agency',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('opportunities', 'response_deadline',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('opportunities', 'posted_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index(op.f('ix_llm_calls_id'), table_name='llm_calls')
    op.drop_constraint(None, 'facility_features', type_='foreignkey')
    op.drop_index(op.f('ix_facility_features_source_doc_id'), table_name='facility_features')
    op.drop_index(op.f('ix_facility_features_id'), table_name='facility_features')
    op.alter_column('facility_features', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('facility_features', 'value',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('facility_features', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('facility_features', 'category')
    op.drop_constraint(None, 'evidence', type_='foreignkey')
    op.drop_constraint(None, 'evidence', type_='foreignkey')
    op.drop_index(op.f('ix_evidence_source_doc_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_requirement_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_id'), table_name='evidence')
    op.create_index(op.f('idx_evidence_requirement_id'), 'evidence', ['requirement_id'], unique=False)
    op.alter_column('evidence', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('evidence', 'snippet',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('evidence', 'source_doc_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('evidence', 'extra_metadata')
    op.drop_constraint(None, 'email_log', type_='foreignkey')
    op.drop_index(op.f('ix_email_log_id'), table_name='email_log')
    op.add_column('documents', sa.Column('processed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('document_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('opportunity_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('file_size', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('download_date', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('document_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('documents_opportunity_id_fkey'), 'documents', 'opportunities', ['opportunity_id'], ['opportunity_id'])
    op.drop_index(op.f('ix_documents_kind'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_column('documents', 'updated_at')
    op.drop_column('documents', 'created_at')
    op.drop_column('documents', 'meta_json')
    op.drop_column('documents', 'path')
    op.drop_column('documents', 'title')
    op.drop_column('documents', 'kind')
    op.add_column('decision_cache', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_decision_cache_id'), table_name='decision_cache')
    op.drop_constraint(None, 'analysis_logs', type_='foreignkey')
    op.drop_index(op.f('ix_analysis_logs_timestamp'), table_name='analysis_logs')
    op.drop_index(op.f('ix_analysis_logs_level'), table_name='analysis_logs')
    op.drop_index(op.f('ix_analysis_logs_id'), table_name='analysis_logs')
    op.drop_index(op.f('ix_analysis_logs_analysis_result_id'), table_name='analysis_logs')
    op.alter_column('analysis_logs', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.add_column('agent_runs', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_agent_runs_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_messages_id'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_created_at'), table_name='agent_messages')
    op.create_table('proposals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('opportunity_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('contact_person', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('contact_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('proposal_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('executive_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('technical_approach', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('project_management', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pricing_strategy', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('risk_management', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('past_performance', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('team_info', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('full_proposal', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.opportunity_id'], name=op.f('proposals_opportunity_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('proposals_pkey'))
    )
    op.create_table('knowledge_facts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('notice_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('schema_version', sa.TEXT(), server_default=sa.text("'sow.learn.v1'::text"), autoincrement=False, nullable=False, comment='JSON şema versiyonu (sow.learn.v1)'),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='JSONB formatında öğrenilen bilgiler (facts, rationales, citations)'),
    sa.Column('source_docs', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Kaynak dokümanlar (filename, sha256, sayfa numaraları)'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('knowledge_facts_pkey')),
    comment='Eklerden öğrenilen bilgiler ve gerekçeleri'
    )
    op.create_index(op.f('idx_kf_schema'), 'knowledge_facts', ['schema_version'], unique=False)
    op.create_index(op.f('idx_kf_notice'), 'knowledge_facts', ['notice_id'], unique=False)
    op.create_index(op.f('idx_kf_gin'), 'knowledge_facts', ['payload'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_kf_created'), 'knowledge_facts', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('hotel_chunks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('notice_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('embedding', postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=True),
    sa.Column('chunk_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('chunk_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('embedding_model_version', sa.VARCHAR(length=50), server_default=sa.text("'sentence-transformers/all-MiniLM-L6-v2'::character varying"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('hotel_chunks_pkey'))
    )
    op.create_index(op.f('idx_hotel_chunks_notice_id'), 'hotel_chunks', ['notice_id'], unique=False)
    op.create_index(op.f('idx_hotel_chunks_embedding_version'), 'hotel_chunks', ['embedding_model_version'], unique=False)
    op.create_table('manual_documents',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('upload_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('notice_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('opportunity_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('analysis_status', sa.VARCHAR(), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('analysis_results', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True)
    )
    op.create_index(op.f('idx_manual_documents_notice_id'), 'manual_documents', ['notice_id'], unique=False)
    op.create_table('summaries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('summary_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('key_points', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('summaries_document_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('summaries_pkey'))
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('page', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_sessions_pkey'))
    )
    op.create_index(op.f('idx_user_sessions_session_id'), 'user_sessions', ['session_id'], unique=False)
    op.create_table('document_analysis_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('opportunity_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('analysis_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('analysis_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('document_analysis_results_pkey')),
    sa.UniqueConstraint('opportunity_id', name=op.f('document_analysis_results_opportunity_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('sow_analysis',
    sa.Column('analysis_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('notice_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('template_version', sa.TEXT(), server_default=sa.text("'v1.0'::text"), autoincrement=False, nullable=False),
    sa.Column('sow_payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('source_docs', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('source_hash', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('analysis_id', name=op.f('sow_analysis_pkey'))
    )
    op.create_index(op.f('uq_sow_notice_template'), 'sow_analysis', ['notice_id', 'template_version'], unique=True)
    op.create_index(op.f('idx_vw_active_sow_notice_id'), 'sow_analysis', ['notice_id'], unique=False, postgresql_where='(is_active = true)')
    op.create_index(op.f('idx_sow_payload_gin'), 'sow_analysis', ['sow_payload'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_sow_capacity'), 'sow_analysis', [sa.literal_column("(sow_payload #>> '{function_space,general_session,capacity}'::text[])")], unique=False, postgresql_where='(is_active = true)')
    op.create_index(op.f('idx_sow_breakout_count'), 'sow_analysis', [sa.literal_column("(sow_payload #>> '{function_space,breakout_rooms,count}'::text[])")], unique=False, postgresql_where='(is_active = true)')
    op.create_index(op.f('idx_sow_active'), 'sow_analysis', ['notice_id', 'is_active', 'updated_at'], unique=False)
    op.create_table('opportunity_docs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('notice_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('kind', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('http_status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bytes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('text_excerpt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('raw_headers', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True)
    )
    op.create_table('osm_cache',
    sa.Column('key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('osm_cache_pkey'))
    )
    op.create_index(op.f('idx_osm_cache_created'), 'osm_cache', ['created_at'], unique=False)
    op.create_table('structured_requirements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('notice_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('requirement_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('requirement_category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('requirement_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('requirement_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('requirement_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('extracted_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('extracted_by', sa.VARCHAR(length=50), server_default=sa.text("'autogen_agent'::character varying"), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('structured_requirements_pkey'))
    )
    op.create_index(op.f('idx_structured_requirements_type'), 'structured_requirements', ['requirement_type'], unique=False)
    op.create_index(op.f('idx_structured_requirements_notice_id'), 'structured_requirements', ['notice_id'], unique=False)
    op.create_index(op.f('idx_structured_requirements_metadata'), 'structured_requirements', ['requirement_metadata'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_structured_requirements_category'), 'structured_requirements', ['requirement_category'], unique=False)
    op.create_index(op.f('idx_structured_requirements_active'), 'structured_requirements', ['is_active'], unique=False)
    op.create_table('keywords',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('keyword', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('keywords_pkey')),
    sa.UniqueConstraint('keyword', name=op.f('keywords_keyword_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('sam_subcontracts',
    sa.Column('subaward_report_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('prime_contract_key', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('piid', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('agency_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('referenced_idv_piid', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('referenced_idv_agency_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('action_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False)
    )
    op.create_table('hotel_opportunities_new',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('notice_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('agency', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('naics_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('posted_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('response_deadline', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('hotel_opportunities_new_pkey')),
    sa.UniqueConstraint('notice_id', name=op.f('hotel_opportunities_new_notice_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('document_opportunity_relations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('opportunity_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('relation_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.opportunity_id'], name=op.f('document_opportunity_relations_opportunity_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('document_opportunity_relations_pkey'))
    )
    op.create_table('hotel_resource_links',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('notice_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('resource_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('resource_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('file_type', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('file_size', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('hotel_resource_links_pkey'))
    )
    op.create_table('system_metrics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('metric_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('metric_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('metric_unit', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('system_metrics_pkey'))
    )
    op.create_table('hotel_suggestions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('notice_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('website', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lon', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('capacity_estimate', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price_estimate', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('distance_km', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('match_score', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('selected', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('hotel_suggestions_pkey'))
    )
    op.create_index(op.f('idx_hs_score'), 'hotel_suggestions', [sa.literal_column('match_score DESC')], unique=False)
    op.create_index(op.f('idx_hs_notice'), 'hotel_suggestions', ['notice_id'], unique=False)
    op.create_index(op.f('idx_hs_geo'), 'hotel_suggestions', ['lat', 'lon'], unique=False)
    op.drop_index(op.f('ix_hotels_status'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_opportunity_id'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_id'), table_name='hotels')
    op.drop_table('hotels')
    op.drop_index(op.f('ix_clauses_id'), table_name='clauses')
    op.drop_index(op.f('ix_clauses_document_id'), table_name='clauses')
    op.drop_table('clauses')
    # ### end Alembic commands ###



